### ISSUE TITLE
Great work！

### ISSUE THREAD

**Issue by MontaEllis** [joannahong/Lip2Wav-pytorch#1]
Hi, I also reproduce Lip2wav with Pytorch. However, the aligned image is quite strange. And the training is very slow. Can I have your e-mail? I would check my repo and yours this week. Maybe I can figure out what I have done wrong.

**Comment by joannahong** [comment]
It took several days for me to train chem dataset. I have not checked quantitative scores, but the results sounded similar to the original repo results. You can email me: joanna2587@kaist.ac.kr. Thank you!
