### ISSUE TITLE
Multi Speaker

### ISSUE THREAD

**Issue by b21727795** [joannahong/Lip2Wav-pytorch#5]
Hi! It is great work.

I just have question about Multi Speaker part. Did you finish the  implementation of all code. While I trying there is mismatch problem due to model sizes. I took image sizes as 64x64 then this problem solved but another problem pop up. Dimensions not exactly correct I guess.

I just wonder do you work on it or these mistakes are special to me ?

**Comment by MertCokelek** [comment]
You should update the hparams (embedding input/output dim) to match the data flow. 
As far as I understood, those parts of the code haven't been completed yet.
I'll share the corresponding values soon.

**Comment by b21727795** [comment]
Thank you Cokelek
