### ISSUE TITLE
How can I avoid the IndexError?

### ISSUE THREAD

**Issue by rita-zeng** [joannahong/Lip2Wav-pytorch#6]
Thanks for this great pytorch project!
I processed the dataset with the original Lip2Wav code 'download_speaker.sh' and 'preprocess.py'. But when I run this pytorch 'train.py' till 4624 liters, it comes to a IndexError. I wonder how can I avoid it? 
Looking forward to your reply!
![image](https://user-images.githubusercontent.com/32928342/121762615-aa0e4a80-cb69-11eb-87eb-194beedc6df3.png)

**Comment by joannahong** [comment]
Hello, can you tell me what dataset you are using for training?
Thank you.

**Comment by rita-zeng** [comment]
Thanks for your reply!
I use the Chemistry Lectures for training.
Firstly I set batchsize=8, the above problem occurs. Then I set the batchsize=1, the following problem occurs.
![image](https://user-images.githubusercontent.com/32928342/121777662-dc4d9580-cbc5-11eb-93bd-81541bbd80f5.png)
The dimension of 'gate_output' is getting smaller while training.

**Comment by rita-zeng** [comment]
This is the dimension changing process of 'gate_output' while batchsize=4. When the size drops to [1,1], the IndexError occurs.
![image](https://user-images.githubusercontent.com/32928342/121777994-63e7d400-cbc7-11eb-9c9d-63d09f5c4963.png)
![image](https://user-images.githubusercontent.com/32928342/121777999-6ba77880-cbc7-11eb-9891-3bc5960fc8de.png)
![image](https://user-images.githubusercontent.com/32928342/121778008-73671d00-cbc7-11eb-8127-7905e82c4fc0.png)
![image](https://user-images.githubusercontent.com/32928342/121778012-7a8e2b00-cbc7-11eb-8d35-25896d6255dd.png)
![image](https://user-images.githubusercontent.com/32928342/121778026-8aa60a80-cbc7-11eb-8837-b2ba8f5c7f1b.png)
![image](https://user-images.githubusercontent.com/32928342/121778038-95f93600-cbc7-11eb-8605-17d869f7a6a0.png)

**Comment by joannahong** [comment]
I usually use 24 batch size for training chemistry lectures. Can you increase batch size just in case?

**Comment by rita-zeng** [comment]
I set the batch size to 22, have trained 8874 liters, it seems work for now. 
Gate_output of size should be [batch size, gate_prediction], right? I still got the problem that  why batch size changes during training? Shouldn't it be a fixed value?

**Comment by joannahong** [comment]
Batch size changes in VMcollate which eliminates ones that do not satisfy the training condition.

**Comment by rita-zeng** [comment]
I see, thanks a lot!
