### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'data_root'

### ISSUE THREAD

**Issue by crankyz** [joannahong/Lip2Wav-pytorch#7]
Hello,
When running test.py, how to avoid this error?

**Comment by joannahong** [comment]
Have you checked parser.parse_args? Isn't it 'data_dir' not 'data_root'?

**Comment by crankyz** [comment]
Yes simple change in parse_args data_dir to data_root and results_dir to results_root take affect, and test passes.
python test.py --data_root=<dir/to/dataset> --results_root=<dir/to/save/results> --checkpoint=<pth/to/model>
